osx_image: xcode9
language: objective-c

cache:
- bundler

before_install:
- rvm install 2.3.3
- gem install cocoapods
- gem install coveralls
- gem install slather
- gem install fastlane --version 2.93.1 --no-document
- gem cleanup

install:
- pod repo update --silent
- pod install --project-directory=Example

script:
- pod lib lint

after_success: 
- cd Example && fastlane test